# Generated by Django 4.0.6 on 2022-09-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wireless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popsite', models.CharField(choices=[('بوتان', 'بوتان'), ('شریعتی', 'شریعتی'), ('زرین', 'زرین'), ('کردستان', 'کردستان'), ('سنایی', 'سنایی'), ('پلاستیران', 'پلاستیران')], max_length=25)),
                ('internet_t_bw', models.BigIntegerField(blank=True, null=True)),
                ('internet_r_bw', models.BigIntegerField(blank=True, null=True)),
                ('interanet_t_bw', models.BigIntegerField(blank=True, null=True)),
                ('interanet_r_bw', models.BigIntegerField(blank=True, null=True)),
                ('throughput_t_bw', models.BigIntegerField(blank=True, null=True)),
                ('throughput_r_bw', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'XLarge'), ('xxlarge', 'XXLarge')], default='medium', max_length=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerservice.customer')),
            ],
        ),
    ]
